### ISSUE TITLE
Add support for Heltec v3 Console Image

### ISSUE THREAD

**Issue by liamcottle** [liamcottle/rnode-flasher#3]
Related to #2

- Need to add the address offset for the console image on this device.
- Need to skip flashing the console image if a user decides to flash an older firmware zip that doesn't include it.

**Comment by markqvist** [comment]
Offset for Heltec v3 is `0x210000`.

**Comment by liamcottle** [comment]
Added in https://github.com/liamcottle/rnode-flasher/commit/117fa16feff1abe0fd0861c0698e82f5ee5b9449.

Turns out the `console_image.bin` was already present in the Heltec v3 firmware zip from when the board was first added to the firmware, it just didn't have the offset in the flasher, and the board itself just didn't know it could run the console image since `HAS_CONSOLE` was false.

This means I don't need to add backward compatibility for when a `console_image.bin` is missing from the firmware zip, since it will always be present for this board.
